### PR TITLE
add docker for local dev

### PR DESCRIPTION
**Pull request by citoki**
REQUEST FOR COMMENTS

_Out of curiosity, I created a docker image for local development. Don't know if this will ever work for Swift based apps._

## Goal for Development within in Docker Container
- code on local machine w/ favorite editor
- test in docker container (slower, regarding build time?) or on local machine (faster?)
- testing environment is the exact same environment as in production

## Build Development Image
- `cd docker`
- build docker image for development, similar to the release build `docker build -t swifttalk-dev ../`
- start development image `docker-compose up -d`
- _optional:_ see logs `docker logs -f $(docker ps | grep swifttalk-dev | awk '{ print $1}')`

**Server Ports**
- Postgres `8760`
- Adminer `8761`
- swifttalk-server `8765`

## Things to consider
- when database password or have to be changed, corresponding volume needs to be removed
- `docker-compose.yml` file doesn't support dynamic env variables, see `RDS_HOSTNAME`
- when npm dependencies changes, corresponding volume has to be removed and container restarted

## TODOs / Status
- watch program like `inotify-tools` for automatic rebuilds on file changes >> incremental builds?
- while some environment vars are missing, the server currently isn't able to start
```sh
Compile Swift Module 'SwiftTalkServerLib' (47 sources)
Compile Swift Module 'swifttalk_server' (1 sources)
Linking ./.build/x86_64-unknown-linux/release/swifttalk-server
ERROR /app/Sources/SwiftTalkServerLib/Migrations.swift:25 The operation could not be completed
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:31: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:31: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:31: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:31: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:31: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:31: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:31: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:31: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Network.swift:29: request failed: https://.recurly.com/v2/plans?
error:Optional(Foundation.URLError(_nsError: Could not resolve host: .recurly.com))
response: nil
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticData.swift:65: Could not load plans from Recurly
ERROR /app/Sources/SwiftTalkServerLib/Network.swift:29: request failed: https://.recurly.com/v2/plans?
error:Optional(Foundation.URLError(_nsError: Could not resolve host: .recurly.com))
response: nil
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticData.swift:65: Could not load plans from Recurly
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:90: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:90: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/ScheduledTasks.swift:19: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Network.swift:29: request failed: https://api.github.com/repos/objcio/swift-talk-static-data/contents/collaborators.json?
error:nil
response: Optional(<HTTPURLResponse 0x00007fbda82ea2b0> { URL: https://api.github.com/repos/objcio/swift-talk-static-data/contents/collaborators.json? }{ status: 401, headers {
   "Content-Security-Policy" = default-src 'none';
   "Content-Length" = 93;
   "X-RateLimit-Remaining" = 57;
   "X-GitHub-Media-Type" = github.v3; param=raw;
   "Referrer-Policy" = origin-when-cross-origin, strict-origin-when-cross-origin;
   "Content-Type" = "application/json; charset=utf-8";
   "Status" = 401 Unauthorized;
   "Date" = Fri, 15 Feb 2019 20:08:53 GMT;
   "Access-Control-Expose-Headers" = ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type;
   "X-Frame-Options" = deny;
   "Strict-Transport-Security" = max-age=31536000; includeSubdomains; preload;
   "Server" = GitHub.com;
   "X-Content-Type-Options" = nosniff;
   "X-RateLimit-Reset" = 1550264877;
   "X-XSS-Protection" = 1; mode=block;
   "X-RateLimit-Limit" = 60;
   "X-GitHub-Request-Id" = 8D03:63D1:144E6D7:29A8318:5C671C54;
   "Access-Control-Allow-Origin" = *;
} })
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:53: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Network.swift:29: request failed: https://api.github.com/repos/objcio/swift-talk-static-data/contents/collections.json?
error:nil
response: Optional(<HTTPURLResponse 0x00007fbda810ced0> { URL: https://api.github.com/repos/objcio/swift-talk-static-data/contents/collections.json? }{ status: 401, headers {
   "Content-Security-Policy" = default-src 'none';
   "Content-Length" = 93;
   "X-RateLimit-Remaining" = 54;
   "X-GitHub-Media-Type" = github.v3; param=raw;
   "Referrer-Policy" = origin-when-cross-origin, strict-origin-when-cross-origin;
   "Content-Type" = "application/json; charset=utf-8";
   "Status" = 401 Unauthorized;
   "Date" = Fri, 15 Feb 2019 20:08:53 GMT;
   "Access-Control-Expose-Headers" = ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type;
   "X-Frame-Options" = deny;
   "Strict-Transport-Security" = max-age=31536000; includeSubdomains; preload;
   "Server" = GitHub.com;
   "X-Content-Type-Options" = nosniff;
   "X-RateLimit-Reset" = 1550264877;
   "X-XSS-Protection" = 1; mode=block;
   "X-RateLimit-Limit" = 60;
   "X-GitHub-Request-Id" = 8BDB:160F:9DA6A8:18FE41B:5C671C54;
   "Access-Control-Allow-Origin" = *;
} })
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:53: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Network.swift:29: request failed: https://api.github.com/repos/objcio/swift-talk-static-data/contents/episodes.json?
error:nil
response: Optional(<HTTPURLResponse 0x00007fbda810ce50> { URL: https://api.github.com/repos/objcio/swift-talk-static-data/contents/episodes.json? }{ status: 401, headers {
   "Content-Security-Policy" = default-src 'none';
   "Content-Length" = 93;
   "X-RateLimit-Remaining" = 55;
   "X-GitHub-Media-Type" = github.v3; param=raw;
   "Referrer-Policy" = origin-when-cross-origin, strict-origin-when-cross-origin;
   "Content-Type" = "application/json; charset=utf-8";
   "Status" = 401 Unauthorized;
   "Date" = Fri, 15 Feb 2019 20:08:53 GMT;
   "Access-Control-Expose-Headers" = ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type;
   "X-Frame-Options" = deny;
   "Strict-Transport-Security" = max-age=31536000; includeSubdomains; preload;
   "Server" = GitHub.com;
   "X-Content-Type-Options" = nosniff;
   "X-RateLimit-Reset" = 1550264877;
   "X-XSS-Protection" = 1; mode=block;
   "X-RateLimit-Limit" = 60;
   "X-GitHub-Request-Id" = F94B:0288:158A7AD:2B0C026:5C671C54;
   "Access-Control-Allow-Origin" = *;
} })
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:53: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Network.swift:29: request failed: https://api.github.com/repos/objcio/swift-talk-static-data/contents/collaborators.json?
error:nil
response: Optional(<HTTPURLResponse 0x00007fbda81fc080> { URL: https://api.github.com/repos/objcio/swift-talk-static-data/contents/collaborators.json? }{ status: 401, headers {
   "Content-Security-Policy" = default-src 'none';
   "Content-Length" = 93;
   "X-RateLimit-Remaining" = 56;
   "X-GitHub-Media-Type" = github.v3; param=raw;
   "Referrer-Policy" = origin-when-cross-origin, strict-origin-when-cross-origin;
   "Content-Type" = "application/json; charset=utf-8";
   "Status" = 401 Unauthorized;
   "Date" = Fri, 15 Feb 2019 20:08:53 GMT;
   "Access-Control-Expose-Headers" = ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type;
   "X-Frame-Options" = deny;
   "Strict-Transport-Security" = max-age=31536000; includeSubdomains; preload;
   "Server" = GitHub.com;
   "X-Content-Type-Options" = nosniff;
   "X-RateLimit-Reset" = 1550264877;
   "X-XSS-Protection" = 1; mode=block;
   "X-RateLimit-Limit" = 60;
   "X-GitHub-Request-Id" = FB29:5B47:10A7A7E:2410EA3:5C671C54;
   "Access-Control-Allow-Origin" = *;
} })
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:53: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Network.swift:29: request failed: https://api.github.com/repos/objcio/swift-talk-static-data/contents/collections.json?
error:nil
response: Optional(<HTTPURLResponse 0x00007fbda8105990> { URL: https://api.github.com/repos/objcio/swift-talk-static-data/contents/collections.json? }{ status: 401, headers {
   "Content-Security-Policy" = default-src 'none';
   "Content-Length" = 93;
   "X-RateLimit-Remaining" = 53;
   "X-GitHub-Media-Type" = github.v3; param=raw;
   "Referrer-Policy" = origin-when-cross-origin, strict-origin-when-cross-origin;
   "Content-Type" = "application/json; charset=utf-8";
   "Status" = 401 Unauthorized;
   "Date" = Fri, 15 Feb 2019 20:08:53 GMT;
   "Access-Control-Expose-Headers" = ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type;
   "X-Frame-Options" = deny;
   "Strict-Transport-Security" = max-age=31536000; includeSubdomains; preload;
   "Server" = GitHub.com;
   "X-Content-Type-Options" = nosniff;
   "X-RateLimit-Reset" = 1550264877;
   "X-XSS-Protection" = 1; mode=block;
   "X-RateLimit-Limit" = 60;
   "X-GitHub-Request-Id" = 0F60:4D9C:959B15:1705FDF:5C671C54;
   "Access-Control-Allow-Origin" = *;
} })
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:53: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Network.swift:29: request failed: https://api.github.com/repos/objcio/swift-talk-static-data/contents/episodes.json?
error:nil
response: Optional(<HTTPURLResponse 0x00007fbda85696c0> { URL: https://api.github.com/repos/objcio/swift-talk-static-data/contents/episodes.json? }{ status: 401, headers {
   "Content-Security-Policy" = default-src 'none';
   "Content-Length" = 93;
   "X-RateLimit-Remaining" = 52;
   "X-GitHub-Media-Type" = github.v3; param=raw;
   "Referrer-Policy" = origin-when-cross-origin, strict-origin-when-cross-origin;
   "Content-Type" = "application/json; charset=utf-8";
   "Status" = 401 Unauthorized;
   "Date" = Fri, 15 Feb 2019 20:08:53 GMT;
   "Access-Control-Expose-Headers" = ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type;
   "X-Frame-Options" = deny;
   "Strict-Transport-Security" = max-age=31536000; includeSubdomains; preload;
   "Server" = GitHub.com;
   "X-Content-Type-Options" = nosniff;
   "X-RateLimit-Reset" = 1550264877;
   "X-XSS-Protection" = 1; mode=block;
   "X-RateLimit-Limit" = 60;
   "X-GitHub-Request-Id" = 719E:786C:16A426E:2C9B89F:5C671C54;
   "Access-Control-Allow-Origin" = *;
} })
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:53: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/Network.swift:38: request failed: _sequence(Networking.CombinedEndpoint<Any>.single(https://api.github.com/repos/objcio/episode-transcripts/contents/?ref=master&access_token=), (Function))
error:nil
response: Optional(<HTTPURLResponse 0x00007fbda839eb20> { URL: https://api.github.com/repos/objcio/episode-transcripts/contents/?ref=master&access_token= }{ status: 404, headers {
   "Content-Security-Policy" = default-src 'none';
   "X-GitHub-Media-Type" = github.v3;
   "X-RateLimit-Remaining" = 51;
   "Referrer-Policy" = origin-when-cross-origin, strict-origin-when-cross-origin;
   "Content-Type" = "application/json; charset=utf-8";
   "Status" = 404 Not Found;
   "Date" = Fri, 15 Feb 2019 20:08:53 GMT;
   "Access-Control-Expose-Headers" = ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type;
   "X-Frame-Options" = deny;
   "Strict-Transport-Security" = max-age=31536000; includeSubdomains; preload;
   "Server" = GitHub.com;
   "Transfer-Encoding" = chunked;
   "X-Content-Type-Options" = nosniff;
   "X-RateLimit-Reset" = 1550264877;
   "X-XSS-Protection" = 1; mode=block;
   "X-RateLimit-Limit" = 60;
   "Content-Encoding" = gzip;
   "Access-Control-Allow-Origin" = *;
   "X-GitHub-Request-Id" = 5D76:648B:14FF4DD:2B21084:5C671C55;
} })
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:98: Failed to load transcripts
ERROR /app/Sources/SwiftTalkServerLib/Network.swift:38: request failed: _sequence(Networking.CombinedEndpoint<Any>.single(https://api.github.com/repos/objcio/episode-transcripts/contents/?ref=master&access_token=), (Function))
error:nil
response: Optional(<HTTPURLResponse 0x00007fbda80860a0> { URL: https://api.github.com/repos/objcio/episode-transcripts/contents/?ref=master&access_token= }{ status: 404, headers {
   "Content-Security-Policy" = default-src 'none';
   "X-GitHub-Media-Type" = github.v3;
   "X-RateLimit-Remaining" = 50;
   "Referrer-Policy" = origin-when-cross-origin, strict-origin-when-cross-origin;
   "Content-Type" = "application/json; charset=utf-8";
   "Status" = 404 Not Found;
   "Date" = Fri, 15 Feb 2019 20:08:53 GMT;
   "Access-Control-Expose-Headers" = ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type;
   "X-Frame-Options" = deny;
   "Strict-Transport-Security" = max-age=31536000; includeSubdomains; preload;
   "Server" = GitHub.com;
   "Transfer-Encoding" = chunked;
   "X-Content-Type-Options" = nosniff;
   "X-RateLimit-Reset" = 1550264877;
   "X-XSS-Protection" = 1; mode=block;
   "X-RateLimit-Limit" = 60;
   "Content-Encoding" = gzip;
   "Access-Control-Allow-Origin" = *;
   "X-GitHub-Request-Id" = 7DDE:3758:178F6C7:2E3B082:5C671C55;
} })
ERROR /app/Sources/SwiftTalkServerLib/Static/StaticHelpers.swift:98: Failed to load transcripts
ERROR /app/Sources/SwiftTalkServerLib/ScheduledTasks.swift:19: The operation could not be completed —
ERROR /app/Sources/SwiftTalkServerLib/ScheduledTasks.swift:19: The operation could not be completed —
```

### CODE REVIEW

**Comment by chriseidhof** [comment]
Hi @citoki, 

This looks pretty cool! I would be hesitant to include the adminer image, I think that might be a bit too much.

**Comment by citoki** [comment]
I just saw in the morning that I had left the adminer php in there from a different project.

Removed now the complete image. As I saw in your videos, both of you are familiar with psql commands. 😄

**Comment by chriseidhof** [comment]
Hey @citoki,

I had a think about it, and one of the problems of merging it is that we won't use this ourselves. As we open-sourced our codebase mostly for educational purposes, I don't think anyone else will use it regularly either.... That means the file will sit in the repository until it stops working, because I'm pretty sure we will forget to maintain it ;). Maybe we can add a section to the README instead, telling people that it's easy to set up a docker-compose file for local development.

**Comment by chriseidhof** [comment]
I've done just that in the current README, so will close this for now. We do really appreciate the effort!

**Pull request closed without merging**
